version: 1
disable_existing_loggers: False
formatters:
  basic:
    (): logginghelper.OneLineExceptionFormatter
    format: "%(message)s"
  pipe:
    format: "%(asctime)s|%(name)s|%(levelname)s|%(message)s"
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console_handler:
    class: logging.StreamHandler
    level: INFO
    formatter: basic
    stream: ext://sys.stdout

  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: NOTSET
    formatter: pipe
    filename: ptxttools.log
    maxBytes: 10485760 # 10MB
    backupCount: 10
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: pipe
    filename: ptxttoolsErrors.log
    maxBytes: 10485760 # 10MB
    backupCount: 10
    encoding: utf8

loggers:
  LoggerName:
    level: INFO
    handlers: [console_handler, file_handler]
    propagate: no

root:
  level: DEBUG
  handlers: [console_handler, file_handler, error_file_handler]

